### ISSUE TITLE
Column name is not bold

### ISSUE THREAD

**Issue by priyanshk20** [bhavesh-pepcoding/Excel-Clone#1]
Column names are not in bold weight because we used `font-weight:"bold";` instead of `font-weight:bold;`

**Comment by priyanshk20** [comment]
Can i fix some small css issues like that? Sir @bhavesh-pepcoding

**Comment by bhavesh-pepcoding** [comment]
Yes definitely

**Comment by priyanshk20** [comment]
@bhavesh-pepcoding Sir changes done, please approve and merge.

**Comment by bhavesh-pepcoding** [comment]
Ok i will do that

**Comment by bhavesh-pepcoding** [comment]
Approved
